---
- name: Install Kubernetes cluster
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
  - name: Update /etc/hosts
    ansible.builtin.blockinfile:
      path: /etc/hosts
      create: yes
      block: |

        {% for item in ansible_play_batch %}
        {{ hostvars[item].ansible_ssh_host }} {{ item }}
        {% endfor %}

- name: Setup the master node
  remote_user: ansible
  hosts: master_node
  become: yes
  roles:
    - master

- name: Join worker nodes to the cluster
  remote_user: ansible
  hosts: worker_nodes
  become: yes
  roles:
    - worker
