---

- name: Set hostname for the server(s)
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Retrieve join command
  ansible.builtin.set_fact:
    join_command: "{{ hostvars['DUMMY_HOST']['kubeadm_join_command'] }}"
  run_once: true

- name: Join node to the cluster
  ansible.builtin.command:
    cmd: "{{ join_command }}"
